version: "2.0"
services:
  nginx:
    build: .
    ports:
      - "80:80"
    volumes:
      - "./index:/data/index"
  web:
    build: ./services/web
    ports:
      - "8088:80"
    volumes:
      - "./services/web:/usr/src/app"
  draw:
    build: ./services/draw
    ports:
      - "8080:80"
    volumes:
      - "./services/draw:/usr/src/app"
  draw-archive:
    build: ./services/draw-archive
    ports:
      - "8081:80"
    volumes:
      - "./data/draw-archive:/usr/data"