version: "2.0"
services:
  http:
    build: .
    ports:
    - "80:80"
    volumes:
    - "./index:/data/index"
  draw:
    build: ./services/draw
    ports:
      - "8080:80"
    volumes:
    - "./services/draw/public:/usr/src/app/public"