version: "2.0"
services:
  http:
    build: .
    ports:
    - "80:80"
  draw:
    build: ./services/draw
    ports:
    - "8080:80"
  draw-archive:
    build: ./services/draw-archive
    ports:
      - "8081:80"
    volumes:
      - "/usr/data/draw-archive:/usr/data"